[versions]
dotenv-kotlin = "6.5.1"
exposed = "1.1.1"
kotlin = "2.4.0"
kotlin-logging = "8.0.4"
logback = "1.5.27"
shadow = "9.3.0"
sqlite-jdbc = "3.53.4.0"
tgbots-module = "9.5.0"
heartbeat = "0.1.0"
twitch4j = "1.26.0"

[libraries]
dotenv-kotlin = { module = "io.github.cdimascio:dotenv-kotlin", version.ref = "dotenv-kotlin" }
exposed-core = { module = "org.jetbrains.exposed:exposed-core", version.ref = "exposed" }
exposed-java-time = { module = "org.jetbrains.exposed:exposed-java-time", version.ref = "exposed" }
exposed-jdbc = { module = "org.jetbrains.exposed:exposed-jdbc", version.ref = "exposed" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin-logging" }
logback-classic = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }
sqlite-jdbc = { module = "org.xerial:sqlite-jdbc", version.ref = "sqlite-jdbc" }
tgbots-module = { module = "com.annimon:tgbots-module", version.ref = "tgbots-module" }
heartbeat = { module = "com.helltar:heartbeat", version.ref = "heartbeat" }
twitch4j = { module = "com.github.twitch4j:twitch4j", version.ref = "twitch4j" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
